version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 

  app:
    build: .
    container_name: node_app
    ports:
      - "3003:3003" 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/vibeo
    depends_on:
      - mongodb

volumes:
  mongodb_data: